// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `app`, `client_for_session`, `collection_key`, `complete_login`, `expire_snapshot_if_needed`, `parse_collection_type`, `refresh_library`, `refresh_tracks`, `require_session`, `session_snapshot`, `validate_collection_key`, `validate_phone`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `App`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

Future<void> initialize({required String dataDirectory}) =>
    RustLib.instance.api.crateApiInitialize(dataDirectory: dataDirectory);

Future<Profile?> restoreSession() =>
    RustLib.instance.api.crateApiRestoreSession();

Future<void> sendLoginCode({
  required String phone,
  required String countryCode,
}) => RustLib.instance.api.crateApiSendLoginCode(
  phone: phone,
  countryCode: countryCode,
);

Future<Profile> loginWithCode({
  required String phone,
  required String countryCode,
  required String code,
}) => RustLib.instance.api.crateApiLoginWithCode(
  phone: phone,
  countryCode: countryCode,
  code: code,
);

Future<QrLoginChallenge> createQrLogin() =>
    RustLib.instance.api.crateApiCreateQrLogin();

Future<QrLoginCheck> checkQrLogin({required String key}) =>
    RustLib.instance.api.crateApiCheckQrLogin(key: key);

Future<LibraryResult> getLibrary({required String category}) =>
    RustLib.instance.api.crateApiGetLibrary(category: category);

Future<List<CollectionSummary>> refreshLibraryNow({required String category}) =>
    RustLib.instance.api.crateApiRefreshLibraryNow(category: category);

Future<TracksResult> getCollectionTracks({
  required String collectionType,
  required String collectionId,
}) => RustLib.instance.api.crateApiGetCollectionTracks(
  collectionType: collectionType,
  collectionId: collectionId,
);

Future<List<Track>> refreshCollectionTracksNow({
  required String collectionType,
  required String collectionId,
}) => RustLib.instance.api.crateApiRefreshCollectionTracksNow(
  collectionType: collectionType,
  collectionId: collectionId,
);

Future<String> getStreamUrl({
  required String collectionKey,
  required String trackId,
}) => RustLib.instance.api.crateApiGetStreamUrl(
  collectionKey: collectionKey,
  trackId: trackId,
);

Future<void> savePlaybackState({
  required String collectionKey,
  required SavedPosition position,
}) => RustLib.instance.api.crateApiSavePlaybackState(
  collectionKey: collectionKey,
  position: position,
);

Future<List<PlaybackRecord>> loadPlaybackState() =>
    RustLib.instance.api.crateApiLoadPlaybackState();

Future<String?> lookupAudioCache({required String trackId}) =>
    RustLib.instance.api.crateApiLookupAudioCache(trackId: trackId);

Future<String> writeAudioCache({
  required String trackId,
  required List<int> bytes,
}) => RustLib.instance.api.crateApiWriteAudioCache(
  trackId: trackId,
  bytes: bytes,
);

Future<String> cacheAudioTrack({
  required String collectionKey,
  required String trackId,
}) => RustLib.instance.api.crateApiCacheAudioTrack(
  collectionKey: collectionKey,
  trackId: trackId,
);

Future<BigInt> audioCacheSize() =>
    RustLib.instance.api.crateApiAudioCacheSize();

Future<void> clearAudioCache() =>
    RustLib.instance.api.crateApiClearAudioCache();

Future<void> clearMediaCache() =>
    RustLib.instance.api.crateApiClearMediaCache();

Future<void> logout() => RustLib.instance.api.crateApiLogout();

class LibraryResult {
  final List<CollectionSummary> items;
  final bool fromCache;

  const LibraryResult({required this.items, required this.fromCache});

  @override
  int get hashCode => items.hashCode ^ fromCache.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LibraryResult &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          fromCache == other.fromCache;
}

class TracksResult {
  final List<Track> items;
  final bool fromCache;

  const TracksResult({required this.items, required this.fromCache});

  @override
  int get hashCode => items.hashCode ^ fromCache.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TracksResult &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          fromCache == other.fromCache;
}
