// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -798699006;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'wyyyy_core',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<BigInt> crateApiAudioCacheSize();

  Future<String> crateApiCacheAudioTrack({
    required String collectionKey,
    required String trackId,
  });

  Future<QrLoginCheck> crateApiCheckQrLogin({required String key});

  Future<void> crateApiClearAudioCache();

  Future<void> crateApiClearMediaCache();

  Future<QrLoginChallenge> crateApiCreateQrLogin();

  Future<TracksResult> crateApiGetCollectionTracks({
    required String collectionType,
    required String collectionId,
  });

  Future<LibraryResult> crateApiGetLibrary({required String category});

  Future<String> crateApiGetStreamUrl({
    required String collectionKey,
    required String trackId,
  });

  Future<void> crateApiInitialize({required String dataDirectory});

  Future<List<PlaybackRecord>> crateApiLoadPlaybackState();

  Future<Profile> crateApiLoginWithCode({
    required String phone,
    required String countryCode,
    required String code,
  });

  Future<void> crateApiLogout();

  Future<String?> crateApiLookupAudioCache({required String trackId});

  Future<List<Track>> crateApiRefreshCollectionTracksNow({
    required String collectionType,
    required String collectionId,
  });

  Future<List<CollectionSummary>> crateApiRefreshLibraryNow({
    required String category,
  });

  Future<Profile?> crateApiRestoreSession();

  Future<void> crateApiSavePlaybackState({
    required String collectionKey,
    required SavedPosition position,
  });

  Future<void> crateApiSendLoginCode({
    required String phone,
    required String countryCode,
  });

  Future<String> crateApiWriteAudioCache({
    required String trackId,
    required List<int> bytes,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<BigInt> crateApiAudioCacheSize() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAudioCacheSizeConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAudioCacheSizeConstMeta =>
      const TaskConstMeta(debugName: "audio_cache_size", argNames: []);

  @override
  Future<String> crateApiCacheAudioTrack({
    required String collectionKey,
    required String trackId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(collectionKey, serializer);
          sse_encode_String(trackId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCacheAudioTrackConstMeta,
        argValues: [collectionKey, trackId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCacheAudioTrackConstMeta => const TaskConstMeta(
    debugName: "cache_audio_track",
    argNames: ["collectionKey", "trackId"],
  );

  @override
  Future<QrLoginCheck> crateApiCheckQrLogin({required String key}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(key, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_qr_login_check,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCheckQrLoginConstMeta,
        argValues: [key],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCheckQrLoginConstMeta =>
      const TaskConstMeta(debugName: "check_qr_login", argNames: ["key"]);

  @override
  Future<void> crateApiClearAudioCache() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiClearAudioCacheConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClearAudioCacheConstMeta =>
      const TaskConstMeta(debugName: "clear_audio_cache", argNames: []);

  @override
  Future<void> crateApiClearMediaCache() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiClearMediaCacheConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClearMediaCacheConstMeta =>
      const TaskConstMeta(debugName: "clear_media_cache", argNames: []);

  @override
  Future<QrLoginChallenge> crateApiCreateQrLogin() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_qr_login_challenge,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCreateQrLoginConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCreateQrLoginConstMeta =>
      const TaskConstMeta(debugName: "create_qr_login", argNames: []);

  @override
  Future<TracksResult> crateApiGetCollectionTracks({
    required String collectionType,
    required String collectionId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(collectionType, serializer);
          sse_encode_String(collectionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_tracks_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiGetCollectionTracksConstMeta,
        argValues: [collectionType, collectionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetCollectionTracksConstMeta =>
      const TaskConstMeta(
        debugName: "get_collection_tracks",
        argNames: ["collectionType", "collectionId"],
      );

  @override
  Future<LibraryResult> crateApiGetLibrary({required String category}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(category, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_library_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiGetLibraryConstMeta,
        argValues: [category],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetLibraryConstMeta =>
      const TaskConstMeta(debugName: "get_library", argNames: ["category"]);

  @override
  Future<String> crateApiGetStreamUrl({
    required String collectionKey,
    required String trackId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(collectionKey, serializer);
          sse_encode_String(trackId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiGetStreamUrlConstMeta,
        argValues: [collectionKey, trackId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetStreamUrlConstMeta => const TaskConstMeta(
    debugName: "get_stream_url",
    argNames: ["collectionKey", "trackId"],
  );

  @override
  Future<void> crateApiInitialize({required String dataDirectory}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dataDirectory, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiInitializeConstMeta,
        argValues: [dataDirectory],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitializeConstMeta =>
      const TaskConstMeta(debugName: "initialize", argNames: ["dataDirectory"]);

  @override
  Future<List<PlaybackRecord>> crateApiLoadPlaybackState() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_playback_record,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiLoadPlaybackStateConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLoadPlaybackStateConstMeta =>
      const TaskConstMeta(debugName: "load_playback_state", argNames: []);

  @override
  Future<Profile> crateApiLoginWithCode({
    required String phone,
    required String countryCode,
    required String code,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(phone, serializer);
          sse_encode_String(countryCode, serializer);
          sse_encode_String(code, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_profile,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiLoginWithCodeConstMeta,
        argValues: [phone, countryCode, code],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLoginWithCodeConstMeta => const TaskConstMeta(
    debugName: "login_with_code",
    argNames: ["phone", "countryCode", "code"],
  );

  @override
  Future<void> crateApiLogout() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiLogoutConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLogoutConstMeta =>
      const TaskConstMeta(debugName: "logout", argNames: []);

  @override
  Future<String?> crateApiLookupAudioCache({required String trackId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(trackId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiLookupAudioCacheConstMeta,
        argValues: [trackId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLookupAudioCacheConstMeta => const TaskConstMeta(
    debugName: "lookup_audio_cache",
    argNames: ["trackId"],
  );

  @override
  Future<List<Track>> crateApiRefreshCollectionTracksNow({
    required String collectionType,
    required String collectionId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(collectionType, serializer);
          sse_encode_String(collectionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_track,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRefreshCollectionTracksNowConstMeta,
        argValues: [collectionType, collectionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRefreshCollectionTracksNowConstMeta =>
      const TaskConstMeta(
        debugName: "refresh_collection_tracks_now",
        argNames: ["collectionType", "collectionId"],
      );

  @override
  Future<List<CollectionSummary>> crateApiRefreshLibraryNow({
    required String category,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(category, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_collection_summary,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRefreshLibraryNowConstMeta,
        argValues: [category],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRefreshLibraryNowConstMeta => const TaskConstMeta(
    debugName: "refresh_library_now",
    argNames: ["category"],
  );

  @override
  Future<Profile?> crateApiRestoreSession() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_profile,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRestoreSessionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRestoreSessionConstMeta =>
      const TaskConstMeta(debugName: "restore_session", argNames: []);

  @override
  Future<void> crateApiSavePlaybackState({
    required String collectionKey,
    required SavedPosition position,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(collectionKey, serializer);
          sse_encode_box_autoadd_saved_position(position, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSavePlaybackStateConstMeta,
        argValues: [collectionKey, position],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSavePlaybackStateConstMeta => const TaskConstMeta(
    debugName: "save_playback_state",
    argNames: ["collectionKey", "position"],
  );

  @override
  Future<void> crateApiSendLoginCode({
    required String phone,
    required String countryCode,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(phone, serializer);
          sse_encode_String(countryCode, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSendLoginCodeConstMeta,
        argValues: [phone, countryCode],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSendLoginCodeConstMeta => const TaskConstMeta(
    debugName: "send_login_code",
    argNames: ["phone", "countryCode"],
  );

  @override
  Future<String> crateApiWriteAudioCache({
    required String trackId,
    required List<int> bytes,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(trackId, serializer);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWriteAudioCacheConstMeta,
        argValues: [trackId, bytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWriteAudioCacheConstMeta => const TaskConstMeta(
    debugName: "write_audio_cache",
    argNames: ["trackId", "bytes"],
  );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  Profile dco_decode_box_autoadd_profile(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_profile(raw);
  }

  @protected
  SavedPosition dco_decode_box_autoadd_saved_position(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_saved_position(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  CollectionSummary dco_decode_collection_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return CollectionSummary(
      id: dco_decode_String(arr[0]),
      collectionType: dco_decode_collection_type(arr[1]),
      title: dco_decode_String(arr[2]),
      subtitle: dco_decode_String(arr[3]),
      coverUrl: dco_decode_String(arr[4]),
      trackCount: dco_decode_opt_box_autoadd_u_32(arr[5]),
    );
  }

  @protected
  CollectionType dco_decode_collection_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CollectionType.values[raw as int];
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  LibraryResult dco_decode_library_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return LibraryResult(
      items: dco_decode_list_collection_summary(arr[0]),
      fromCache: dco_decode_bool(arr[1]),
    );
  }

  @protected
  List<CollectionSummary> dco_decode_list_collection_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_collection_summary).toList();
  }

  @protected
  List<PlaybackRecord> dco_decode_list_playback_record(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_playback_record).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<Track> dco_decode_list_track(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_track).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  Profile? dco_decode_opt_box_autoadd_profile(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_profile(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  PlaybackRecord dco_decode_playback_record(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return PlaybackRecord(
      collectionKey: dco_decode_String(arr[0]),
      position: dco_decode_saved_position(arr[1]),
    );
  }

  @protected
  Profile dco_decode_profile(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return Profile(
      id: dco_decode_String(arr[0]),
      nickname: dco_decode_String(arr[1]),
      avatarUrl: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  QrLoginChallenge dco_decode_qr_login_challenge(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return QrLoginChallenge(
      key: dco_decode_String(arr[0]),
      imageDataUrl: dco_decode_String(arr[1]),
    );
  }

  @protected
  QrLoginCheck dco_decode_qr_login_check(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return QrLoginCheck(
      status: dco_decode_String(arr[0]),
      profile: dco_decode_opt_box_autoadd_profile(arr[1]),
    );
  }

  @protected
  SavedPosition dco_decode_saved_position(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return SavedPosition(
      trackId: dco_decode_String(arr[0]),
      trackIndex: dco_decode_u_32(arr[1]),
      position: dco_decode_f_64(arr[2]),
      updatedAt: dco_decode_u_64(arr[3]),
    );
  }

  @protected
  Track dco_decode_track(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return Track(
      id: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      artist: dco_decode_String(arr[2]),
      duration: dco_decode_f_64(arr[3]),
      coverUrl: dco_decode_opt_String(arr[4]),
    );
  }

  @protected
  TracksResult dco_decode_tracks_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return TracksResult(
      items: dco_decode_list_track(arr[0]),
      fromCache: dco_decode_bool(arr[1]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  Profile sse_decode_box_autoadd_profile(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_profile(deserializer));
  }

  @protected
  SavedPosition sse_decode_box_autoadd_saved_position(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_saved_position(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  CollectionSummary sse_decode_collection_summary(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_collectionType = sse_decode_collection_type(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_subtitle = sse_decode_String(deserializer);
    var var_coverUrl = sse_decode_String(deserializer);
    var var_trackCount = sse_decode_opt_box_autoadd_u_32(deserializer);
    return CollectionSummary(
      id: var_id,
      collectionType: var_collectionType,
      title: var_title,
      subtitle: var_subtitle,
      coverUrl: var_coverUrl,
      trackCount: var_trackCount,
    );
  }

  @protected
  CollectionType sse_decode_collection_type(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return CollectionType.values[inner];
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  LibraryResult sse_decode_library_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_items = sse_decode_list_collection_summary(deserializer);
    var var_fromCache = sse_decode_bool(deserializer);
    return LibraryResult(items: var_items, fromCache: var_fromCache);
  }

  @protected
  List<CollectionSummary> sse_decode_list_collection_summary(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <CollectionSummary>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_collection_summary(deserializer));
    }
    return ans_;
  }

  @protected
  List<PlaybackRecord> sse_decode_list_playback_record(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <PlaybackRecord>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_playback_record(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<Track> sse_decode_list_track(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Track>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_track(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Profile? sse_decode_opt_box_autoadd_profile(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_profile(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlaybackRecord sse_decode_playback_record(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_collectionKey = sse_decode_String(deserializer);
    var var_position = sse_decode_saved_position(deserializer);
    return PlaybackRecord(
      collectionKey: var_collectionKey,
      position: var_position,
    );
  }

  @protected
  Profile sse_decode_profile(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_nickname = sse_decode_String(deserializer);
    var var_avatarUrl = sse_decode_opt_String(deserializer);
    return Profile(
      id: var_id,
      nickname: var_nickname,
      avatarUrl: var_avatarUrl,
    );
  }

  @protected
  QrLoginChallenge sse_decode_qr_login_challenge(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_key = sse_decode_String(deserializer);
    var var_imageDataUrl = sse_decode_String(deserializer);
    return QrLoginChallenge(key: var_key, imageDataUrl: var_imageDataUrl);
  }

  @protected
  QrLoginCheck sse_decode_qr_login_check(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_status = sse_decode_String(deserializer);
    var var_profile = sse_decode_opt_box_autoadd_profile(deserializer);
    return QrLoginCheck(status: var_status, profile: var_profile);
  }

  @protected
  SavedPosition sse_decode_saved_position(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_trackId = sse_decode_String(deserializer);
    var var_trackIndex = sse_decode_u_32(deserializer);
    var var_position = sse_decode_f_64(deserializer);
    var var_updatedAt = sse_decode_u_64(deserializer);
    return SavedPosition(
      trackId: var_trackId,
      trackIndex: var_trackIndex,
      position: var_position,
      updatedAt: var_updatedAt,
    );
  }

  @protected
  Track sse_decode_track(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_artist = sse_decode_String(deserializer);
    var var_duration = sse_decode_f_64(deserializer);
    var var_coverUrl = sse_decode_opt_String(deserializer);
    return Track(
      id: var_id,
      title: var_title,
      artist: var_artist,
      duration: var_duration,
      coverUrl: var_coverUrl,
    );
  }

  @protected
  TracksResult sse_decode_tracks_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_items = sse_decode_list_track(deserializer);
    var var_fromCache = sse_decode_bool(deserializer);
    return TracksResult(items: var_items, fromCache: var_fromCache);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_profile(Profile self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_profile(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_saved_position(
    SavedPosition self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_saved_position(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_collection_summary(
    CollectionSummary self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_collection_type(self.collectionType, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.subtitle, serializer);
    sse_encode_String(self.coverUrl, serializer);
    sse_encode_opt_box_autoadd_u_32(self.trackCount, serializer);
  }

  @protected
  void sse_encode_collection_type(
    CollectionType self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_library_result(LibraryResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_collection_summary(self.items, serializer);
    sse_encode_bool(self.fromCache, serializer);
  }

  @protected
  void sse_encode_list_collection_summary(
    List<CollectionSummary> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_collection_summary(item, serializer);
    }
  }

  @protected
  void sse_encode_list_playback_record(
    List<PlaybackRecord> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_playback_record(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_track(List<Track> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_track(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_profile(
    Profile? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_profile(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_playback_record(
    PlaybackRecord self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.collectionKey, serializer);
    sse_encode_saved_position(self.position, serializer);
  }

  @protected
  void sse_encode_profile(Profile self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.nickname, serializer);
    sse_encode_opt_String(self.avatarUrl, serializer);
  }

  @protected
  void sse_encode_qr_login_challenge(
    QrLoginChallenge self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.key, serializer);
    sse_encode_String(self.imageDataUrl, serializer);
  }

  @protected
  void sse_encode_qr_login_check(QrLoginCheck self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.status, serializer);
    sse_encode_opt_box_autoadd_profile(self.profile, serializer);
  }

  @protected
  void sse_encode_saved_position(SavedPosition self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.trackId, serializer);
    sse_encode_u_32(self.trackIndex, serializer);
    sse_encode_f_64(self.position, serializer);
    sse_encode_u_64(self.updatedAt, serializer);
  }

  @protected
  void sse_encode_track(Track self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.artist, serializer);
    sse_encode_f_64(self.duration, serializer);
    sse_encode_opt_String(self.coverUrl, serializer);
  }

  @protected
  void sse_encode_tracks_result(TracksResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_track(self.items, serializer);
    sse_encode_bool(self.fromCache, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
