// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  Profile dco_decode_box_autoadd_profile(dynamic raw);

  @protected
  SavedPosition dco_decode_box_autoadd_saved_position(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  CollectionSummary dco_decode_collection_summary(dynamic raw);

  @protected
  CollectionType dco_decode_collection_type(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  LibraryResult dco_decode_library_result(dynamic raw);

  @protected
  List<CollectionSummary> dco_decode_list_collection_summary(dynamic raw);

  @protected
  List<PlaybackRecord> dco_decode_list_playback_record(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<Track> dco_decode_list_track(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  Profile? dco_decode_opt_box_autoadd_profile(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  PlaybackRecord dco_decode_playback_record(dynamic raw);

  @protected
  Profile dco_decode_profile(dynamic raw);

  @protected
  QrLoginChallenge dco_decode_qr_login_challenge(dynamic raw);

  @protected
  QrLoginCheck dco_decode_qr_login_check(dynamic raw);

  @protected
  SavedPosition dco_decode_saved_position(dynamic raw);

  @protected
  Track dco_decode_track(dynamic raw);

  @protected
  TracksResult dco_decode_tracks_result(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  Profile sse_decode_box_autoadd_profile(SseDeserializer deserializer);

  @protected
  SavedPosition sse_decode_box_autoadd_saved_position(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  CollectionSummary sse_decode_collection_summary(SseDeserializer deserializer);

  @protected
  CollectionType sse_decode_collection_type(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  LibraryResult sse_decode_library_result(SseDeserializer deserializer);

  @protected
  List<CollectionSummary> sse_decode_list_collection_summary(
    SseDeserializer deserializer,
  );

  @protected
  List<PlaybackRecord> sse_decode_list_playback_record(
    SseDeserializer deserializer,
  );

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<Track> sse_decode_list_track(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  Profile? sse_decode_opt_box_autoadd_profile(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  PlaybackRecord sse_decode_playback_record(SseDeserializer deserializer);

  @protected
  Profile sse_decode_profile(SseDeserializer deserializer);

  @protected
  QrLoginChallenge sse_decode_qr_login_challenge(SseDeserializer deserializer);

  @protected
  QrLoginCheck sse_decode_qr_login_check(SseDeserializer deserializer);

  @protected
  SavedPosition sse_decode_saved_position(SseDeserializer deserializer);

  @protected
  Track sse_decode_track(SseDeserializer deserializer);

  @protected
  TracksResult sse_decode_tracks_result(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_profile(Profile self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_saved_position(
    SavedPosition self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_collection_summary(
    CollectionSummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_collection_type(
    CollectionType self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_library_result(LibraryResult self, SseSerializer serializer);

  @protected
  void sse_encode_list_collection_summary(
    List<CollectionSummary> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_playback_record(
    List<PlaybackRecord> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_track(List<Track> self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_profile(
    Profile? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_playback_record(
    PlaybackRecord self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_profile(Profile self, SseSerializer serializer);

  @protected
  void sse_encode_qr_login_challenge(
    QrLoginChallenge self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_qr_login_check(QrLoginCheck self, SseSerializer serializer);

  @protected
  void sse_encode_saved_position(SavedPosition self, SseSerializer serializer);

  @protected
  void sse_encode_track(Track self, SseSerializer serializer);

  @protected
  void sse_encode_tracks_result(TracksResult self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
