// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class CollectionSummary {
  final String id;
  final CollectionType collectionType;
  final String title;
  final String subtitle;
  final String coverUrl;
  final int? trackCount;

  const CollectionSummary({
    required this.id,
    required this.collectionType,
    required this.title,
    required this.subtitle,
    required this.coverUrl,
    this.trackCount,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      collectionType.hashCode ^
      title.hashCode ^
      subtitle.hashCode ^
      coverUrl.hashCode ^
      trackCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CollectionSummary &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          collectionType == other.collectionType &&
          title == other.title &&
          subtitle == other.subtitle &&
          coverUrl == other.coverUrl &&
          trackCount == other.trackCount;
}

enum CollectionType { album, playlist, podcast }

class PlaybackRecord {
  final String collectionKey;
  final SavedPosition position;

  const PlaybackRecord({required this.collectionKey, required this.position});

  @override
  int get hashCode => collectionKey.hashCode ^ position.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlaybackRecord &&
          runtimeType == other.runtimeType &&
          collectionKey == other.collectionKey &&
          position == other.position;
}

class Profile {
  final String id;
  final String nickname;
  final String? avatarUrl;

  const Profile({required this.id, required this.nickname, this.avatarUrl});

  @override
  int get hashCode => id.hashCode ^ nickname.hashCode ^ avatarUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Profile &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          nickname == other.nickname &&
          avatarUrl == other.avatarUrl;
}

class QrLoginChallenge {
  final String key;
  final String imageDataUrl;

  const QrLoginChallenge({required this.key, required this.imageDataUrl});

  @override
  int get hashCode => key.hashCode ^ imageDataUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QrLoginChallenge &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          imageDataUrl == other.imageDataUrl;
}

class QrLoginCheck {
  final String status;
  final Profile? profile;

  const QrLoginCheck({required this.status, this.profile});

  @override
  int get hashCode => status.hashCode ^ profile.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QrLoginCheck &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          profile == other.profile;
}

class SavedPosition {
  final String trackId;
  final int trackIndex;
  final double position;
  final BigInt updatedAt;

  const SavedPosition({
    required this.trackId,
    required this.trackIndex,
    required this.position,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      trackId.hashCode ^
      trackIndex.hashCode ^
      position.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SavedPosition &&
          runtimeType == other.runtimeType &&
          trackId == other.trackId &&
          trackIndex == other.trackIndex &&
          position == other.position &&
          updatedAt == other.updatedAt;
}

class Track {
  final String id;
  final String title;
  final String artist;
  final double duration;
  final String? coverUrl;

  const Track({
    required this.id,
    required this.title,
    required this.artist,
    required this.duration,
    this.coverUrl,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      artist.hashCode ^
      duration.hashCode ^
      coverUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Track &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          artist == other.artist &&
          duration == other.duration &&
          coverUrl == other.coverUrl;
}
